### ISSUE TITLE
Layout Issue: Shapes outside component

### ISSUE THREAD

**Issue by StefMar13** [SiEPIC/openEBL-2024-07-Si-Heaters#37]
Hello,

I keep getting the same layout error for my design, but I am unsure why... one is on the heater portion for my tapered ring (first screenshot), and the other 3 are outside of the floorplan (second screenshot)... I am not sure how to fix these. Please advise.

First error (in the area of my tapered ring):
![image](https://github.com/user-attachments/assets/46bf1427-45a1-4820-8898-6d53c94be0f4)

Remaining 3 errors (just outside the floorplan):
![image](https://github.com/user-attachments/assets/06cc3bfa-efaa-4b72-a346-2e653b9c38ad)

**Comment by lukasc-ubc** [comment]
Let me check, but we can probably waive these results.  The intent was to get designers to put all the shapes/polygons inside a cell, rather than drawing metal on top of optical devices.

**Comment by StefMar13** [comment]
Okay, I see, thank you!

**Comment by lukasc-ubc** [comment]
I fixed it in SiEPIC-Tools v0.5.10.
