### ISSUE TITLE
Question About .yaml verification failure and Routines

### ISSUE THREAD

**Issue by StefMar13** [SiEPIC/openEBL-2024-07-Si-Heaters#39]
In my pull requests I have been facing the following .yaml verification error (in addition to layout errors I mentioned in a separate Issue):

![WhatsApp Image 2024-07-12 at 13 33 51_7d875c1d](https://github.com/user-attachments/assets/f5285b06-014c-4b30-9b13-e8dbd04ce917)

Could it be because there are no "Routines" in my .yaml file? How could I go about fixing this? 

Thank you!

**Comment by alistairhp** [comment]
i also ran into this error and fixed it by adding 
`Routines:
    []`
to the bottom of my yaml file.

**Comment by lukasc-ubc** [comment]
I fixed the YAML check to look for Sequences instead of Routines.
