### ISSUE TITLE
.yaml verification issue

### ISSUE THREAD

**Issue by gillrobyn** [SiEPIC/openEBL-2024-07-Si-Heaters#52]
Hi there, I've been struggling with the following error during .yaml verification. I'm wondering what I'm doing wrong here?

![Capture](https://github.com/user-attachments/assets/a837c49b-b7b2-4db3-9709-94378dedf737)

**Comment by lukasc-ubc** [comment]
Thanks for reporting this.  This problem is on my end. I hopefully fixed it.
